<html>
	<head>
		<title>Lab 1</title>
		<link rel="stylesheet" href="../styles/form_page.css">
	</head>
	<body>
	<?php
			$properties_file_path = "./../data/db_properties.txt";
			$conn_string = file_get_contents($properties_file_path);
			echo "$conn_string !!!!";
			$db_connection = pg_connect($conn_string);
			if ($db_connection) {
				echo '<br>Connection attempt succeeded.';
				
				$script_time = microtime(true) - $start_time;
				$current_time = date("H:M:S");
				
				$send_new_point_result = pg_query($db_connection, "create table webLab1(id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, x INT NOT NULL, y REAL NOT NULL, r REAL NOT NULL, result BOOL NOT NULL, time VARCHAR(10), scriptTime REAL);");
			} else {
				echo '<br> Connection attempt failed.';
			}
			pg_close($db_connection);
	?>
	</body>
</html>
